// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBricks.Work.SqlServer;

#nullable disable

namespace ServiceBricks.Work.SqlServer.Migrations
{
    [DbContext(typeof(WorkSqlServerContext))]
    partial class WorkSqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Work")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceBricks.Work.EntityFrameworkCore.Process", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FutureProcessDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsError")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ProcessDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProcessQueue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Key");

                    b.ToTable("Process", "Work");
                });
#pragma warning restore 612, 618
        }
    }
}
