// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBricks.Work.Sqlite;

#nullable disable

namespace ServiceBricks.Work.Sqlite.Migrations
{
    [DbContext(typeof(WorkSqliteContext))]
    [Migration("20250124125555_WorkV1")]
    partial class WorkV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ServiceBricks.Work.EntityFrameworkCore.Process", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CreateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("FutureProcessDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessData")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProcessDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ProcessQueue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessType")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UpdateDate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.ToTable("Process");
                });
#pragma warning restore 612, 618
        }
    }
}
